# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(558, 340)
        self.user_label = QtWidgets.QLabel(Form)
        self.user_label.setGeometry(QtCore.QRect(40, 110, 61, 21))
        self.user_label.setObjectName("user_label")
        self.pass_label = QtWidgets.QLabel(Form)
        self.pass_label.setGeometry(QtCore.QRect(40, 161, 51, 21))
        self.pass_label.setObjectName("pass_label")
        self.user_lineEdit = QtWidgets.QLineEdit(Form)
        self.user_lineEdit.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.pwd_lineEdit = QtWidgets.QLineEdit(Form)
        self.pwd_lineEdit.setGeometry(QtCore.QRect(120, 160, 111, 20))
        self.pwd_lineEdit.setObjectName("pwd_lineEdit")
        self.user_textBrowser = QtWidgets.QTextBrowser(Form)
        self.user_textBrowser.setGeometry(QtCore.QRect(260, 50, 256, 201))
        self.user_textBrowser.setObjectName("user_textBrowser")
        self.login_Button = QtWidgets.QPushButton(Form)
        self.login_Button.setGeometry(QtCore.QRect(40, 220, 75, 23))
        self.login_Button.setObjectName("login_Button")
        self.logoff_button = QtWidgets.QPushButton(Form)
        self.logoff_button.setGeometry(QtCore.QRect(150, 220, 75, 23))
        self.logoff_button.setObjectName("logoff_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "这是我的第一个窗口"))
        self.user_label.setText(_translate("Form", "用户名："))
        self.pass_label.setText(_translate("Form", "密　码："))
        self.login_Button.setText(_translate("Form", "确认"))
        self.logoff_button.setText(_translate("Form", "退出"))
